---
- hosts: 127.0.0.1
  vars:
    blackbox_tcp: 'True'
    blackbox_tcp_targets:
      teamA:
        - is-int-nft-external.sas.int-nft.eu.summerott.com:443
        - acdc-int-nft.sas.int-nft.eu.summerott.com:443
        - atom.int-nft.skyshowtime.com:443
        - cybertron-external-gtm.id.int-nft.summerott.com:443
        - pay-assist-int-nft.sas.int-nft.eu.summerott.com:443
      teamB:
        - am-int-nft.sas.int-nft.eu.summerott.com:443
        - pm-int-nft-external.sas.int-nft.eu.summerott.com:443
        - sas.int-nft.eu.summerott.com:443            
        - auth-external-gtm.ovp.int-nft.eu.summerott.com:443
        - ls-external-gtm.ovp.int-nft.eu.summerott.com:443
        - rango-external-gtm.id.int-nft.eu.summerott.com:443
        - ott-ppg-int-nft-external.sas.int-nft.eu.summerott.com:443
        - commerce-hm-int-nft.sas.int-nft.eu.summerott.com:443
        - s-pay-alm01-int-nft.plsse.eu-central-1.stage.eu-aws.summerinfra.com:443
  tasks:
    - name: Jinja 2 template tester
      template:
        src: test_template.j2
        dest: output_template.txt
